sir:
  _target_: envs.SirEnvironment
  population: 10_000_000
  beta:  0.000000036
  gamma: 0.1
  S0: 9_999_990
  I0: 10
  v_min: 0
  v_max: 500_000
  v_total_max: 5_000_000
  vaccine_importance: 1.0
  continuous: true
  tf: 300
  dt: 1.0

n_steps: 15_000_000


defaults:
  - override hydra/launcher: joblib

hydra:
  job:
    chdir: true