sir:
  _target_: envs.SirEnvironment
  population: 50_000_001
  beta: 0.0000000132339796
  gamma: 0.33084949
  S0: 50_000_000
  I0: 1
  v_min: 0.0
  v_max: 1.0
  vaccine_importance: 1.0
  continuous: true
  tf: 300
  dt: 1.0

n_steps: 6_000_000


defaults:
  - override hydra/launcher: joblib

hydra:
  job:
    chdir: true