algorithm: PPO

sliar:
  _target_: envs.SliarEnvironment

  S0: 1000000
  L0: 0
  I0: 1
  A0: 0
  population: 1000001

  kappa: 0.526
  alpha: 0.244
  p: 0.667
  eta: 0.244
  epsilon: 0
  q: 0.5
  delta: 1
  R0: 1.9847
  tf: 300
  dt: 5
  P: 1
  Q: 1000000
  R: 1000000
  W: 1000000
  continuous: false

  nu_min: 0.0
  tau_min: 0.0
  sigma_min: 0.0

  nu_max: 0.01
  tau_max: 0.05
  sigma_max: 0.01

n_steps: 5000

hydra:
  job:
    chdir: true

defaults:
  - override hydra/launcher: joblib